title: helloworld
description: 创建一个名为GitHub slideshow的存储库
template:
  repo: helloworld-template
  name: helloworld
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
